# Generated by Django 4.0.3 on 2023-03-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_sale_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='employee_number',
            field=models.IntegerField(unique=True),
        ),
    ]
